server:
  port: 8092
spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/customer_service
    username: root
    password: Sunny@7712
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
eureka:
  client:
    register-with-eureka: true
  service-url: http://localhost:8761/eureka/
